services:
  backend:
    build: ./backend
    container_name: taskbloom-backend
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend
    container_name: taskbloom-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
