services:
  backend:
    build: ./backend
    image: waleedrehman31/taskbloom-backend:latest
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    image: waleedrehman31/taskbloom-frontend:latest
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://34.229.154.220:5001
