apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskbloom-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: waleedrehman31/backend:latest
          ports:
            - containerPort: 5001
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: NODE_ENV
              value: "production"
